require"plugins/suda"
require"plugins/slash"
require"plugins/lualine"
require"plugins/trouble"
require"plugins/telescope"
require"plugins/livecommand"
require"plugins/colorizer"
require"plugins/neodev"
