#!/bin/sh
# demolinux VM control script
#  Usage: ./dctrl [shell|pull{,nvim,awesome}|push] [src [dest]]

common_opts=( 60022 -o StrictHostKeyChecking=no -o LogLevel=quiet )

shell(){
	if [ -n "$1" ]; then
		ssh -p ${common_opts[@]} demostanis@localhost "$*"
	else
		ssh -p ${common_opts[@]} demostanis@localhost
	fi
}

pull(){
	scp -rP ${common_opts[@]} demostanis@localhost:"$1" "${2:-.}"
}

push(){
	scp -rP ${common_opts[@]} "$1" demostanis@localhost:"${2:-.}"
}

case $1 in
	shell) shell "${@:2}" ;;
	pull) pull "${@:2}" ;;
	push) push "${@:2}" ;;

	# shorthands
	pullnvim) pull '.config/nvim/*' airootfs/etc/skel/.config/nvim ;;
	pullawesome) pull '.config/awesome/*' airootfs/etc/skel/.config/awesome ;;
	pullbookmarks) pull '.mozilla/firefox/default.profile/bookmarks.html' airootfs/etc/skel/.mozilla/firefox/default.profile ;;

	*) sed -n '2,3s/# //p' "$0" ;;
esac
