#!/bin/sh
# demolinux build&run script
#  Usage: ./demolinux [run|clean|build|all|flash|schemes]

A=( $@ )
elevate(){
	[ $(id -u) -ne 0 ] && exec sudo -E ./"$0" ${A[@]}
}

clean(){
	elevate
	pkill archiso
	mount | grep $PWD | cut -d\  -f3 | xargs -r umount -l
	umount -fl /mnt/demolinux/* 2>/dev/null
	losetup -d /dev/loop0 2>/dev/null
	rm -rf work/
}

ensure_installed(){
	pacman -Q $(<build_packages) >/dev/null || {
		echo Missing packages to build. Installing...
		pacman -S --noconfirm $(<build_packages)
	}
}

rebuild_schemes(){
	XDG_CONFIG_HOME=$PWD without_root flavours -c flavours/flavours.conf apply ${1:-mellow-purple}
}

build(){
	ensure_installed
	elevate
	./bin/mkarchiso -o out/ -w work/ -v .
}

run(){
	without_root ./bin/run_archiso -i out/$(ls -t out/ | head -1)
}

flash(){
	elevate
	device=${1:?Missing device}
	pv out/$(ls -t out/ | head -1) > "$device"
	sync
}

without_root(){
	if [ $(id -u) -ne 0 ]; then
		$@
	else
		su $SUDO_USER -pc "$*"
	fi
}

case $1 in
	run) run ;;
	clean) clean ;;
	build) clean; build ;;
	schemes) rebuild_schemes $2 ;;
	flash) flash $2 ;;
	all) clean; rebuild_schemes && build && run ;;
	*) sed -n '2,3s/# //p' "$0" ;;
esac
