#!/bin/sh
# demolinux build&run script
#  Usage: ./demolinux [run|clean|build|all|flash|schemes]

A=( $@ )
elevate(){
	[ $(id -u) -ne 0 ] && exec sudo -E ./"$0" ${A[@]}
}

clean(){
	elevate
	pkill archiso
	mount | grep $PWD | cut -d\  -f3 | xargs -r umount -l
	umount -fl /mnt/demolinux/* 2>/dev/null
	losetup -d /dev/loop0 2>/dev/null
	rm -rf work/
}

ensure_installed(){
	pacman -Q $(<build_packages) >/dev/null || {
		echo Missing packages to build. Installing...
		pacman -S --noconfirm $(<build_packages)
	}
}

rebuild_schemes(){
	XDG_CONFIG_HOME=$PWD without_root flavours -c flavours/flavours.conf apply ${1:-mellow-purple} ||\
		([ ! "$2" = second_try ] &&
			(echo Fetching schemes and templates...
			without_root flavours update all # >/dev/null 2>&1
			rebuild_schemes "$1" second_try))
}

build(){
	ensure_installed
	elevate
	./bin/mkarchiso -o out/ -w work/ -v .
}

run(){
	without_root ./bin/run_archiso -i out/$(ls -t out/ | head -1)
}

prog="$0"
flash(){
	elevate
	device=${1:?Missing device}
	image=$(ls -t out/ | head -1)
	cmp -jfslkdjflfskddddd >/dev/null 2>&1 # ensure cmp is in the kernel cache
										   # if we're overwritting the device
										   # demolinux runs on
	pv out/"$image" > "$device"
	sync; sync; sync # just to be sure
	if ! cmp -n `stat -c %s out/"$image"` out/"$image" "$device"; then
		echo Image has been incorrectly copied, retrying...
		"$prog" "$0" "$@"
	fi
}

without_root(){
	if [ $(id -u) -ne 0 ]; then
		$@
	else
		su $SUDO_USER -pc "$*"
	fi
}

case $1 in
	run) run ;;
	clean) clean ;;
	build) clean; build ;;
	schemes) rebuild_schemes $2 ;;
	flash) flash $2 ;;
	all) clean; rebuild_schemes && build && run ;;
	*) sed -n '2,3s/# //p' "$0" ;;
esac
