#!/bin/bash

# generate a 1 second blank video
ffmpeg -f lavfi \
	-i color=c=black:s=640x480:d=1 \
	-c:v libx264 \
	-tune stillimage \
	-pix_fmt yuv420p \
	/tmp/output.mp4 >/dev/null 2>&1

mpv-hardened --loop-file=inf /tmp/output.mp4 >/tmp/mpv.log 2>&1 &
player=$!
expectwin 'output.mp4 - mpv' 20
activatewin 'output.mp4 - mpv'
quitwin
wait "$player"
