#!/bin/bash

expectmusic() {
	awesome-client 'show_panel()'

	music=
	tries=${2:-10}
	for i in {1..$tries}; do
		music=$(awesome-client 'return screen.primary.mypanel:get_children_by_id("music-player-message")[1].text' | cut -d\" -f2)

		if [[ "$music" = *"$1"* ]]; then
			xdotool key Escape
			return
		fi

		sleep 1
	done

	echo expected music to be $1 but got $music
	exit 1
}

expectmusic "Not playing"

# Avoid automatic track changes while waiting for MPRIS metadata under load.
ffmpeg -f lavfi -y -i sine=frequency=440:duration=60 \
	-metadata title='demolinux song' \
	-metadata artist='demostanis' \
	~/music/test1.mp3 >/dev/null 2>&1
ffmpeg -f lavfi -y -i sine=frequency=440:duration=60 \
	-metadata title='demolinoox song' \
	-metadata artist='demostanus' \
	~/music/test2.mp3 >/dev/null 2>&1

rhythmbox >/dev/null 2>&1 &
expectwin Rhythmbox
sleep 5

rhythmbox-client --play-uri "file://$HOME/music/test1.mp3"
sleep 1

expectmusic 'demostanis - demolinux song'
rhythmbox-client --play-uri "file://$HOME/music/test2.mp3"
expectmusic 'demostanus - demolinoox song'

quitwin

# this is currently broken on GitHub Actions...
#freetube >/dev/null 2>&1 &
#expectwin 'Subscriptions - FreeTube'
#for i in {1..7}; do xdotool key Tab; sleep 0.1; done
#
#xdotool type 'Animal Crossing Music + Rain Sounds'
#xdotool key Enter
#
#for i in {1..13}; do xdotool key Tab; sleep 0.1; done
#xdotool key Enter
#sleep 60
#xdotool mousemove 480 420 click 1
#sleep 10
#
#expectmusic "Animal Crossing"
#quitwin
