#!/bin/bash

sudo pacman -S --noconfirm tesseract-data-eng >/dev/null 2>&1

expectmusic() {
	awesome-client 'show_panel()'

	music=
	tries=${2:-60}
	for i in {1..$tries}; do
		music=$(import -window root -crop 409x147+8+442 png:- | tesseract - - 2>/dev/null)

		if [[ "$music" = *"$1"* ]]; then
			xdotool key Escape
			return
		fi

		sleep 1
	done

	echo expected music to be $1 but got $music
	exit 1
}

expectmusic "Not playing"

ffmpeg -f lavfi -y -i sine=frequency=440:duration=3 \
	-metadata title='demolinux song' \
	-metadata artist='demostanis' \
	~/music/test1.mp3 >/dev/null 2>&1
ffmpeg -f lavfi -y -i sine=frequency=440:duration=3 \
	-metadata title='demolinoox song' \
	-metadata artist='demostanus' \
	~/music/test2.mp3 >/dev/null 2>&1

rhythmbox >/dev/null 2>&1 &
expectwin Rhythmbox
# even if the window is created, it might not mean
# it's visible..
sleep 1

# play button
xdotool mousemove 100 100
xdotool click 1
sleep 1

expectmusic 'demostanis - demolinux song'
sleep 4
expectmusic 'demostanus - demolinoox song'

quitwin

# this is currently broken on GitHub Actions...
#freetube >/dev/null 2>&1 &
#expectwin 'Subscriptions - FreeTube'
#for i in {1..7}; do xdotool key Tab; sleep 0.1; done
#
#xdotool type 'Animal Crossing Music + Rain Sounds'
#xdotool key Enter
#
#for i in {1..13}; do xdotool key Tab; sleep 0.1; done
#xdotool key Enter
#sleep 60
#xdotool mousemove 480 420 click 1
#sleep 10
#
#expectmusic "Animal Crossing"
#quitwin
