#!/bin/bash

errors=$(nvim --headless +:messages +:q 2>&1)

if [ -n "$errors" ]; then
	echo got errors when launching neovim: "$errors"
	exit 1
fi

pushd `mktemp -d`>/dev/null
echo '{}' > deno.json # required by the deno LSP which we're testing against

nvim --listen /tmp/nvim-tests.sock --headless >/dev/null 2>&1 & pid=$!
trap 'kill $pid; rm -f /tmp/nvim-tests.sock' EXIT
sleep 1

expectvim() {
	nvim \
		--server /tmp/nvim-tests.sock \
		--remote-send "$1" \
		>/dev/null 2>&1 </dev/null

	out=
	tries=${3:-10}
	for i in {1..$tries}; do
		out=$(nvim \
			--server /tmp/nvim-tests.sock \
			--remote-expr "join(getline(1,'$'),'\n')" \
			2>&1 </dev/null)

		[[ "$out" = ${~2} ]] && return
		sleep 1
	done
	echo expected nvim output of \"$1\" to be \"$2\" but got \"$out\" >&2
	exit 1
}

expectvim "ihello world<esc>" "hello world"
expectvim "dd" ""
expectvim "<space>fde" "> de" # telescope prompt
sleep 1
expectvim "<cr>" "{}" # pick deno.json
expectvim ":e main.ts<cr>:w<cr>" ""
sleep 5 # wait for LSP to start (else K will show a man page)
expectvim "iconsole.log<esc>K" "console.log"
expectvim "K" '*Outputs a message to the console*'
expectvim ":q<cr>dd" ""

expectvim "<c-t>" "*demostanis on demolinux*"
expectvim "echo hello" "*demostanis on demolinux*hello*"
expectvim "<c-t>" ""

expectvim ":e main.go<cr>:w<cr>" ""
expectvim "imain" "main"
sleep 1 # wait for the completion popup, it's async
expectvim "<tab><cr>" "func main()*"
expectvim 'fmt.Println<esc>:w<cr>' "package main*import*main*" # goimports
expectvim "Lo" "󰊕  main" # outline
expectvim "<esc>ggdGia<esc>" "a" # remapped esc in outline to close it
expectvim "-" "deno.json*main.go*main.ts" # vinegar opens netrw
expectvim "<c-o>" "a"

popd>/dev/null
