#!/bin/bash

errors=$(nvim --headless +:messages +:q 2>&1)

if [ -n "$errors" ]; then
	echo got errors when launching neovim: "$errors"
	exit 1
fi

pushd `mktemp -d`>/dev/null
echo '{}' > deno.json # required by the deno LSP which we're testing against

nvim --listen /tmp/nvim-tests.sock --headless >/dev/null 2>&1 & pid=$!
trap 'kill $pid; rm -f /tmp/nvim-tests.sock' EXIT
sleep 1

expectvim() {
	nvim \
		--server /tmp/nvim-tests.sock \
		--remote-send "$1" \
		>/dev/null 2>&1 </dev/null

	out=
	tries=${3:-10}
	for i in {1..$tries}; do
		out=$(nvim \
			--server /tmp/nvim-tests.sock \
			--remote-expr "join(getline(1,'$'),'\n')" \
			2>&1 </dev/null)

		[[ "$out" = ${~2} ]] && return
		sleep 1
	done
	echo expected nvim output of \"$1\" to be \"$2\" but got \"$out\" >&2
	exit 1
}

expectvim "ihello world<esc>" "hello world"
expectvim "dd" ""
expectvim "<space>fde" "> de" # telescope prompt
sleep 1
expectvim "<cr>" "{}" # pick deno.json
expectvim ":e main.ts<cr>:w<cr>" ""
sleep 1 # wait for LSP to start
expectvim "iconsole.log<esc>K" "console.log"
sleep 1 # wait for the popup
expectvim "K" '*Outputs a message to the console*'
expectvim ":q<cr>dd" ''

popd>/dev/null
