#!/bin/zsh

stop_vm() {
	echo stopping demolinux...
	pkill archiso_0 2>/dev/null
	rm -f .demolinux_out.log
}

die() {
	[ $# != 0 ] && echo "$*" >&2
	echo awesome log:
	timeout 2 ./dctrl shell "cat ~/.awesome.log"
	timeout 3 ./dctrl pull /data/screenshot.png
	stop_vm
	echo tests failed
	exit 1
}

cd "$(dirname "$(realpath "$0")")"/..

run() {
	set +o pipefail
	(./demolinux __headless | cat -v | tee .demolinux_out.log) || kill -USR1 $$
}

trap 'die failed to run demolinux. did you run ./demolinux build first\?' USR1
run &

# can't use timeout 60 zsh -c ... since signal
# handlers won't be called...
start=$(date +%s)
while :; do
	now=$(date +%s)
	if (( now - start >= 240 )); then
		die VM did not start after 4 minutes.
	fi

	[ -t ] && reset
	echo waiting for guest...
	timeout 2 ./dctrl shell "exit 42"
	# this is mystery...
	ret=$?
	[ $ret = 42 ] && break
	sleep 1
done

echo running demolinux tests...
if ! timeout 30 ./dctrl shell <<EOC; then
while :; do
	if grep 'awesomeWM started' ~/.awesome.log 2>/dev/null; then
		exit
	fi
	sleep 1
done
EOC
	die AwesomeWM did not start after 30 seconds.
fi

echo changing display resolution...
./dctrl shell 'DISPLAY=:0 /usr/lib/xrandr.sh >/dev/null 2>&1'

# for the screen to refresh
sleep 5

./dctrl shell "mkdir /tmp/tests"
( cd tests; for t in ${*:-*}; do ../dctrl push "$t" /tmp/tests >/dev/null; done )
./dctrl push tests/utils /tmp/tests >/dev/null

./dctrl shell <<'EOC' || die

export DISPLAY=:0
cd /tmp/tests
. ./utils

# wait for pacman to work
sudo systemctl start pacman-init

# picom xrender backend doesn't refresh the whole screen correctly in QEMU
while true; do xrefresh; sleep 1; done >/dev/null 2>&1 &

while read -r test; do
	if [ "$test" != ./run -a "$test" != ./utils \
		-a "$test" != ./sysupdate -a "$test" != ./sysupdate_snapshot ]; then
		echo running $test...
		(
			set -e
			trap '
				import -window root png:- > /data/screenshot.png
				kill ${${(v)jobstates##*:*:}%=*} 2>/dev/null || :
			' EXIT
			. "$test"
		)
		if [ $? != 0 ]; then
			echo $test failed 2>&1
			exit 1
		fi
	fi
done < <(find . -type f -executable | sort)

EOC

if [[ $# == 0 || "$*" == *sysupdate* ]]; then
	./dctrl shell "sudo mount -o remount,rw /run/archiso/bootmnt"
	./dctrl shell "sudo sed -i s/timeout=5/timeout=-1/ /run/archiso/bootmnt/grub/grub.cfg"

	# will reboot the VM
	timeout 5 ./dctrl shell "cd /tmp/tests && . ./sysupdate &!" 2>/dev/null

	tries=120
	found=
	for i in {1..$tries}; do
		if grep -q 'sysupdate test succeeded' .demolinux_out.log; then
			found=y
			break
		fi
		sleep 1
	done
	[ -z "$found" ] && die sysupdate failed

	sleep 10 # time to get in the grub menu
	( . ./tests/sysupdate_snapshot )
	ret=$?
	if [ "$ret" != 0 ]; then
		die sysupdate snapshot failed
	fi
fi

echo all tests succeeded
stop_vm
