#!/bin/zsh

stop_vm() {
	echo stopping demolinux...
	pkill archiso_0 2>/dev/null
}

die() {
	[ $# != 0 ] && echo "$*" >&2
	echo awesome log:
	timeout 2 ./dctrl shell "cat ~/.awesome.log"
	timeout 3 ./dctrl shell "DISPLAY=:0 import -window root png:-" > screenshot.png
	stop_vm
	echo tests failed
	exit 1
}

cd "$(dirname "$(realpath "$0")")"/..

run() {
	./demolinux __headless || kill -USR1 $$
}

trap 'die failed to run demolinux. did you run ./demolinux build first\?' USR1
run &

# can't use timeout 60 zsh -c ... since signal
# handlers won't be called...
start=$(date +%s)
while :; do
	now=$(date +%s)
	if (( now - start >= 180 )); then
		die VM did not start after 3 minutes.
	fi

	[ -t ] && reset
	echo waiting for guest...
	timeout 2 ./dctrl shell "exit 42"
	# this is mystery...
	ret=$?
	[ $ret = 42 ] && break
	sleep 1
done

echo running demolinux tests...
if ! timeout 30 ./dctrl shell <<EOC; then
while :; do
	if grep 'awesomeWM started' ~/.awesome.log 2>/dev/null; then
		exit
	fi
	sleep 1
done
EOC
	die AwesomeWM did not start after 30 seconds.
fi

echo changing display resolution...
./dctrl shell 'DISPLAY=:0 /usr/lib/xrandr.sh >/dev/null 2>&1'

# for the screen to refresh
sleep 5

./dctrl push tests /tmp/tests >/dev/null

./dctrl shell <<'EOC' || die

export DISPLAY=:0
cd /tmp/tests
. ./utils

while read -r test; do
	if [ "$test" != ./run -a "$test" != ./utils ]; then
		echo running $test...
		(
			set -e
			trap 'kill ${${(v)jobstates##*:*:}%=*} 2>/dev/null || :' EXIT
			. "$test"
		)
		if [ $? != 0 ]; then
			echo $test failed 2>&1
			exit 1
		fi
	fi
done < <(find . -type f -executable)

EOC

echo all tests succeeded
stop_vm
