#!/bin/bash

started=$SECONDS
sudo systemctl start pacman-init
echo "Package-key setup wait took $((SECONDS - started)) seconds"

failed=$(systemctl --failed -q)

if [ -n "$failed" ]; then
	echo systemd services failed >&2
	echo $failed >&2
	exit 1
fi
