#!/bin/bash

expect_middle_color() {
	mc=
	tries=${2:-10}
	for i in {1..$tries}; do
		mc=$(import -window root png:- | magick png:- -format "%[pixel:p{%[fx:int(w/2)],%[fx:int(h/2)]}]" info:)

		if [ "$mc" = "$1" ]; then
			return
		fi
		sleep 1
	done
	echo expected color at the middle of the screen to be $1 but got $mc
	exit 1
}

yad &
sleep 1
expect_middle_color "srgb(26,9,45)"
quitwin

kdeconnect-app >/dev/null 2>&1 &
sleep 3
modkeypress w
expectfocus "KDE Connect"
expect_middle_color "srgb(51,15,65)"
quitwin

modkeypress Enter
modkeypress Enter
modkeypress h
modkeypress minus

# resizes window to the right (bigger)
xdotool mousemove $(xdotool getdisplaygeometry | awk '{printf("%d %d", $1/2, $2/2)}') sleep 1 \
	keydown Super_L mousedown 3 sleep 1 \
	mousemove_relative 200 0 sleep 1 \
	mouseup 3 keyup Super_L
# focused terminal
expect_middle_color "srgb(30,5,40)"

# resizes window to the left (smaller)
xdotool mousemove $(xdotool getdisplaygeometry | awk '{printf("%d %d", $1/2-100, $2/2)}') sleep 1 \
	keydown Super_L mousedown 3 sleep 1 \
	mousemove_relative -- -500 0 sleep 1 \
	mouseup 3 keyup Super_L
# unfocused terminal
expect_middle_color "srgb(21,4,28)"

quitwin
quitwin
