#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later

build() {
    add_module "cdrom"
    add_module "loop"
    add_module "dm-snapshot"
    add_module "overlay"
    add_module "btrfs"

    add_runscript

    add_binary blockdev
    add_binary dmsetup
    add_binary losetup
    add_binary openssl
    add_binary btrfs
    add_binary plymouth
    add_binary lsblk
    add_binary growpart
    # growpart deps
    add_binary sgdisk
    add_binary flock
    add_binary kexec

    if command -v pv >/dev/null 2>&1; then
        add_binary pv
    else
        warning 'pv not found; falling back to cp for copy to RAM'
    fi

    add_udev_rule 60-cdrom_id.rules
    add_udev_rule 10-dm.rules
    add_udev_rule 95-dm-notify.rules
    add_udev_rule /usr/lib/initcpio/udev/11-dm-initramfs.rules

    if [[ -v ARCHISO_GNUPG_FD ]]; then
        add_binary gpg
        add_dir '/gpg' 0700
        gpg --homedir "$BUILDROOT/gpg" --import <&"$ARCHISO_GNUPG_FD"
    fi
    if [[ -v ARCHISO_TLS_FD ]]; then
        cat <&"$ARCHISO_TLS_FD" >"${BUILDROOT}/codesign.crt"
    fi
    if [[ -v ARCHISO_TLSCA_FD ]]; then
        cat <&"$ARCHISO_TLSCA_FD" >"${BUILDROOT}/codesign_CA.crt"
    fi
}
