#!/bin/bash

sorted_windows() {
	xwininfo -root -tree | \
		grep urxvt | awk -F'["+]' '
		{gsub(/(^ +)|( +$)/,"",$2);print $10 " " $2}
		' | sort -n | cut -d' ' -f2-
}

modkeypress Enter
modkeypress Enter
modkeypress Enter

modkeypress h
modkeypress h
modkeypress equal

for win in {1..3}; do
	xdotool type 'echo window '$win'; sleep infinity'
	xdotool key Enter

	modkeypress Tab
done

assert_windows() {
	actual="$(sorted_windows)"
	expected=$1

	if [ "$actual" != "$expected" ]; then
		echo expected window list to be $expected, but got $actual
		exit 1
	fi
}

assert_windows 'echo window 1; sleep infinity
echo window 2; sleep infinity
echo window 3; sleep infinity'

modkeypress L
assert_windows 'echo window 2; sleep infinity
echo window 1; sleep infinity
echo window 3; sleep infinity'

modkeypress H
assert_windows 'echo window 1; sleep infinity
echo window 2; sleep infinity
echo window 3; sleep infinity'

modkeypress l
modkeypress l
expectfocus "echo window 3; sleep infinity "

modkeypress h
expectfocus "echo window 2; sleep infinity "

quitwin
quitwin
quitwin
