#!/bin/bash

sorted_windows() {
	xwininfo -root -tree | \
		grep urxvt | awk -F'["+]' '
		{gsub(/(^ +)|( +$)/,"",$2);print $10 " " $2}
		' | sort -n | cut -d' ' -f2-
}

for win in {1..3}; do
	urxvt -title "layout window $win" -e sleep infinity &
	expectwin "layout window $win"
	expectfocus "layout window $win"
	expectviewport
done

modkeypress h
expectfocus "layout window 2"
expectviewport
modkeypress h
expectfocus "layout window 1"
expectviewport
modkeypress equal
expectawesome 'return client.focus.width < client.focus.screen.geometry.width / 3 + 5'

for win in 2 3 1; do
	modkeypress Tab
	expectfocus "layout window $win"
done

assert_windows() {
	expected=$1
	for _ in {1..100}; do
		actual="$(sorted_windows)"
		[ "$actual" = "$expected" ] && return
		sleep 0.1
	done
	echo expected window list to be $expected, but got $actual
	exit 1
}

assert_windows 'layout window 1
layout window 2
layout window 3'

modkeypress L
assert_windows 'layout window 2
layout window 1
layout window 3'

modkeypress H
assert_windows 'layout window 1
layout window 2
layout window 3'

modkeypress l
modkeypress l
expectfocus "layout window 3"

modkeypress h
expectfocus "layout window 2"

quitwin
quitwin
quitwin
