#!/bin/bash

expectnofocus() {
	expectawesome 'return client.focus == nil'
}

# overview used to have an issue where the focused window
# would be out of view
expectfocusandleftmost() {
	expectawesome 'return overview_shown ~= true'
	expectfocus "$1"
	expectviewport
}

spawndummywin() {
	yad --class="nonfloating" --title="$1" &
	expectwin "$1"
	expectfocus "$1"
	expectviewport
}

openoverview() {
	modkeypress o
	expectawesome 'return overview_shown == true'
}

expectawesome 'return #client.get() == 0'
modkeypress o
expectawesome 'return overview_shown ~= true'
expectnofocus

spawndummywin "single window"
modkeypress o
expectawesome 'return overview_shown ~= true'
expectfocusandleftmost "single window"
quitwin
expectawesome 'return #client.get() == 0'

spawndummywin "window 1"
spawndummywin "window 2"

openoverview
xdotool key f
expectfocusandleftmost "window 1"

openoverview
xdotool key j
expectfocusandleftmost "window 2"

# no results
openoverview
xdotool key space
expectnofocus
xdotool key BackSpace
xdotool key j
expectfocusandleftmost "window 2"

quitwin
expectfocusandleftmost 'window 1'
quitwin
expectawesome 'return #client.get() == 0'

# more windows than fjdksla, so we get fffjfd..
for i in {1..8}; do
	spawndummywin "dummy $i"
done
openoverview
xdotool key f
expectnofocus
xdotool key f
expectfocusandleftmost 'dummy 1'
for i in {1..8}; do
	quitwin
done
expectawesome 'return #client.get() == 0'
