#!/usr/bin/ash
#
# SPDX-License-Identifier: GPL-3.0-or-later

rundir=/run/archiso

# args: lowerdir=, upperdir=, workdir=, mountpoint=
_mnt_overlayfs() {
    local lowerdir="${1##lowerdir=}"
    local upperdir="${2##upperdir=}"
    local workdir="${3##workdir=}"
    local mountpoint="${4##mountpoint=}"
    mount -t overlay -o \
        "lowerdir=${lowerdir},upperdir=${upperdir},workdir=${workdir},index=off,metacopy=off" \
        airootfs "${mountpoint}"
}

# args: /path/to/image_file, mountpoint
_mnt_fs() {
    local img="${1}"
    local mnt="${2}"
    local img_fullname="${img##*/}"
    local img_loopdev

    # shellcheck disable=SC2154
    # defined via initcpio's parse_cmdline()
    if [ "${copytoram}" = "y" ]; then
        msg -n ":: Copying rootfs image to RAM..."

        if [ "$rc" != 0 ]; then
            echo "ERROR: while copy '${img}' to '$rundir/copytoram/${img_fullname}'"
            launch_interactive_shell
        fi

        img="$rundir/copytoram/${img_fullname}"
        msg "done."
    fi
    img_loopdev="$(losetup --find --show --read-only -- "${img}")"
    _mnt_dev "${img_loopdev}" "${mnt}" "-r" "defaults"
}

# args: device, mountpoint, flags, opts
_mnt_dev() {
    local dev="${1}"
    local mnt="${2}"
    local flg="${3}"
    local opts="${4}"
    local resolved_dev

    msg ":: Mounting '${dev}' to '${mnt}'"

    while ! resolved_dev="$(rootdelay="${rootdelay:-30}" resolve_device "${dev}")"; do
        echo "ERROR: '${dev}' device did not show up after ${rootdelay:-30} seconds..."
        echo "   Falling back to interactive prompt"
        echo "   You can try to fix the problem manually, log out when you are finished"
        launch_interactive_shell
    done

    # If the tag is supported by mount, pass it as is. Otherwise, use the resolved device path.
    case "${dev}" in
        'UUID='* | 'LABEL='* | 'PARTUUID='* | 'PARTLABEL='*) : ;;
        *) dev="${resolved_dev}" ;;
    esac
    if mount --mkdir -o "${opts}" "${flg}" "${dev}" "${mnt}"; then
        msg ":: Device '${dev}' mounted successfully."
    else
        echo "ERROR; Failed to mount '${dev}'"
        echo "   Falling back to interactive prompt"
        echo "   You can try to fix the problem manually, log out when you are finished"
        launch_interactive_shell
    fi
}

run_hook() {
    [ -z "${arch}" ] && arch="$(uname -m)"
    [ -z "${copytoram}" ] && copytoram="auto"
    [ -z "${copytoram_size}" ] && copytoram_size="75%"
    [ -z "${archisobasedir}" ] && archisobasedir="arch"
    [ -z "${archisodevice}" ] && archisodevice="/dev/disk/by-label/${archisolabel}"
    [ -z "${cow_spacesize}" ] && cow_spacesize=$(free | awk '{if(NR==2)print int($2/2/10000)"G"}')

    # set mount handler for archiso
    export mount_handler="archiso_mount_handler"
}

# This function is called normally from init script, but it can be called
# as chain from other mount handlers.
# args: /path/to/newroot
archiso_mount_handler() {
    local newroot="${1}"
    local fs_img fs_img_size iso_blockdev

    btrfs_root=$rundir/btrfs
    _mnt_dev /dev/disk/by-partlabel/system $btrfs_root "-w" "subvol=system,compress=zstd"

    # yes, this syntax is required...
    if [ $(( $(btrfs subvol list $btrfs_root | wc -l) < 6 )) = 1 ]; then
        plymouth update --status="Extending filesystems..."

        # first, resize the filesystem
        umount -f $btrfs_root
        # then, resize the partition to fit the whole disk...
        # TODO: multiple system partitions
        disk=/dev/"$(lsblk -no pkname /dev/disk/by-partlabel/system)"
        growpart "$disk" 3
        partprobe "$disk"

        plymouth update --status="Creating Btrfs subvolumes..."

        _mnt_dev /dev/disk/by-partlabel/system $btrfs_root "-w" "subvol=system,compress=zstd"
        btrfs filesystem resize max $btrfs_root

        # finally, create the necessary subvolumes
        btrfs subvol create $btrfs_root/persistfs
        btrfs subvol create $btrfs_root/snapshots
        btrfs subvol create $btrfs_root/data
        btrfs subvol create $btrfs_root/swap
        btrfs filesystem mkswapfile --size 4G --uuid clear $btrfs_root/swap/swapfile 2>/dev/null
    fi

    if ! mountpoint -q "$rundir/bootmnt"; then
        _mnt_dev /dev/disk/by-partlabel/boot "$rundir/bootmnt" "-w" "defaults"
        offset_magic=99999199999
        if grep $offset_magic $rundir/bootmnt/grub/grub.cfg; then
             plymouth update --status="Updating boot params for hibernation..."
             _mnt_dev /dev/disk/by-partlabel/boot "$rundir/bootmnt" "-w" "defaults"
             offset=$(btrfs inspect-internal map-swapfile -r $rundir/btrfs/swap/swapfile)
             sed -i 's/'$offset_magic'/'$offset/ $rundir/bootmnt/grub/grub.cfg
             cmdline=$(sed 's/'$offset_magic'/'$offset/ /proc/cmdline)
             kexec -l $rundir/bootmnt/vmlinuz-linux --initrd=$rundir/bootmnt/initramfs-linux.img --command-line="$cmdline"
             kexec -e
        else
             _mnt_dev /dev/disk/by-partlabel/boot "$rundir/bootmnt" "-r" "defaults,remount"
        fi
    fi

    _mnt_dev /dev/disk/by-partlabel/system $rundir/data "-w" "subvol=/system/data,compress=zstd,noatime"
    update_img=$rundir/data/sysupdate/demolinux.img
    if [ -e $update_img ]; then
        plymouth update --status="Updating demolinux..."
        img_loopdev="$(losetup -P --find --show -- "$update_img")"
        _mnt_dev "$img_loopdev"p3 $rundir/sysupdate "-w" "defaults,subvol=/system/airootfs"
        # it should be ro by default, but while developping this the current
        # image on github doesn't have its airootfs as read-only...
        btrfs property set $rundir/sysupdate ro true
        btrfs subvolume snapshot $btrfs_root/airootfs $btrfs_root/snapshots/snapshot-$(date +%d-%m-%Y)
        btrfs subvol delete $btrfs_root/airootfs
        btrfs send $rundir/sysupdate | pv | btrfs receive $btrfs_root

        umount $rundir/sysupdate
        rm -rf $rundir/data/sysupdate
        losetup -d "$img_loopdev"
    fi

    plymouth update --status="Mouting filesystems..."
    _mnt_dev /dev/disk/by-partlabel/system $rundir/persistfs "-w" "subvol=/system/persistfs,compress=zstd,noatime"
    _mnt_dev /dev/disk/by-partlabel/system $rundir/snapshots "-w" "subvol=/system/snapshots,compress=zstd,noatime"
    _mnt_dev /dev/disk/by-partlabel/system $rundir/data "-w" "subvol=/system/data,compress=zstd,noatime"
    snapshot="${btrfs_snapshot##*/}"
    snapshot="${snapshot:+snapshots/$snapshot}"
    _mnt_dev /dev/disk/by-partlabel/system $rundir/airootfs "-r" "subvol=/system/${snapshot:-airootfs},compress=zstd,noatime"
    _mnt_dev /dev/disk/by-partlabel/system $rundir/swap "-w" "subvol=/system/swap,compress=zstd,noatime"

    for dir in $rundir/airootfs/etc/skel/*; do
        if readlink "$dir" | grep -q '^/data'; then
            mkdir -p $rundir/data/"$(basename "$(readlink "$dir")")"
        fi
    done
    chown 1000:1000 $rundir/data $rundir/data/*

    # Enable copytoram if the following conditions apply:
    # * the root file system image is not on an optical disc drive,
    # * the root file system image size is less than 4 GiB,
    # * the estimated available memory is more than the root file system image size + 2 GiB.
    if [ "${copytoram}" = "auto" ]; then
        iso_blockdev="$(realpath "$(resolve_device /dev/disk/by-partlabel/system)")"
        if [ "$iso_blockdev" = "${iso_blockdev##/dev/sr}" ]; then
            fs_img_size="$(du -bsk "$rundir/airootfs" | cut -f 1)"
            if [ "$(awk '$1 == "MemAvailable:" { print $2 }' /proc/meminfo)" -gt $((fs_img_size + 2097152)) ]; then
                copytoram="y"
            fi
        fi
    fi
    if [ "${copytoram}" = "y" ]; then
        msg ":: Mounting $rundir/copytoram (tmpfs) filesystem, size=${copytoram_size}"
        mount --mkdir -t tmpfs -o "size=${copytoram_size}",mode=0755 copytoram $rundir/copytoram
    fi

    # why doesnt {cowspace,persistfs} work...
    mkdir -p $rundir/cowspace/upperdir
    mkdir -p $rundir/cowspace/workdir
    mkdir -p $rundir/persistfs/upperdir
    mkdir -p $rundir/persistfs/workdir
    mkdir -p $rundir/cowspace/lowerdir

    lowerdir=$rundir/airootfs
    if [ "$copytoram" = y ]; then
           plymouth update --status="Copying airootfs to RAM..."
            cp -a $rundir/airootfs/* $rundir/copytoram
            lowerdir=$rundir/copytoram
    fi
    _mnt_overlayfs lowerdir=$lowerdir upperdir=$rundir/persistfs/upperdir workdir=$rundir/persistfs/workdir mountpoint=$rundir/cowspace/lowerdir
    _mnt_overlayfs lowerdir=$rundir/cowspace/lowerdir upperdir=$rundir/cowspace/upperdir workdir=$rundir/cowspace/workdir mountpoint="$newroot/"
    umount $btrfs_root
}

# vim: set ft=sh:
