name: default

on:
  push:
    branches:
      - master
      - trigger

jobs:
  nightly:
    if: github.ref == 'refs/heads/trigger'
    permissions: write-all # for releasing
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - name: Set up pacman
        run: ./.github/setup-pacman.sh

      - name: Generate a temporary SSH key for tests
        run: yes | ssh-keygen -f ~/.ssh/id_ed25519 -q -N ''

      - name: Build an image
        run: ./demolinux build

      - name: Run tests
        run: |
          sudo rm -rf work packages
          # we make a copy so the released image isn't one that has
          # been tampered with
          sudo cp -a out/demolinux*.img out/test-demolinux.img
          sudo truncate -s 10G out/test-demolinux.img
          ./demolinux tests
          sudo rm out/test-demolinux.img

      - name: Delete the temporary SSH key
        run: rm -f  ~/.ssh/id_ed25519{,.pub}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        name: Upload screenshot
        if: failure()
        with:
          name: screenshot
          path: screenshot.png

      - name: Split image into chunks
        run: |
          split -b 2GB out/demolinux*.img demolinux-

      - name: Generate checksums file
        run: |
          sha256sum demolinux-* out/demolinux*.img > sha256sums.txt

      - name: Publish release
        uses: andelf/nightly-release@5834076edc55cc05975561c9722043f072ac5c26 # main
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: nightly
          name: Nightly release
          body: |
            Automatically built from GitHub actions, from the master branch.
            Probably unstable.
            The image was split into smaller chunks to fit in GitHub releases, you can reassemble it with cat:
              cat demolinux-* > demolinux.img
          files: |
            ./demolinux-*
            ./sha256sums.txt

  release:
    if: github.ref == 'refs/heads/master'
    permissions: write-all # for releasing
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - name: Set up pacman
        run: ./.github/setup-pacman.sh

      - name: Generate a temporary SSH key for tests
        run: yes | ssh-keygen -f ~/.ssh/id_ed25519 -q -N ''

      - name: Build an image
        run: ./demolinux build

      - name: Run tests
        run: |
          sudo rm -rf work packages
          # we make a copy so the released image isn't one that has
          # been tampered with
          sudo cp -a out/demolinux*.img out/test-demolinux.img
          sudo truncate -s 10G out/test-demolinux.img
          ./demolinux tests
          sudo rm out/test-demolinux.img

      - name: Delete the temporary SSH key
        run: rm -f  ~/.ssh/id_ed25519{,.pub}

      - name: Split image into chunks
        run: |
          split -b 2GB out/demolinux*.img demolinux-

      - name: Generate checksums file
        run: |
          sha256sum demolinux-* out/demolinux*.img > sha256sums.txt

      - name: Publish release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: refs/tags/master-${{ github.sha }}
          release_name: Release build
          body: |
            Automatically built from GitHub actions, from the master branch.
            Shouldn't be unstable.
            The image was split into smaller chunks to fit in GitHub releases, you can reassemble it with cat:
              cat demolinux-* > demolinux.img
      - uses: xresloader/upload-to-github-release@7c5757a90c0bcf0c0e1741da8f2abd7b85e675d0 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "demolinux-*;sha256sums.txt"
          release_id: ${{ steps.create_release.outputs.id }}
