name: default

on:
  push:
    branches:
      - master
      - trigger

jobs:
  nightly:
    if: github.ref == 'refs/heads/trigger'
    permissions: write-all # for releasing
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up pacman
        run: ./.github/setup-pacman.sh

      - name: Build an image
        run: ./demolinux build

      - name: Run tests
        run: ./demolinux tests

      - name: Split image into chunks
        run: |
          split -b 2GB out/demolinux*.img demolinux-

      - name: Generate checksums file
        run: |
          sha256sum demolinux-* out/demolinux*.img > sha256sums.txt

      - name: Publish release
        uses: andelf/nightly-release@main
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: nightly
          name: Nightly release
          body: |
            Automatically built from GitHub actions, from the master branch.
            Probably unstable.
            The image was split into smaller chunks to fit in GitHub releases, you can reassemble it with cat:
              cat demolinux-* > demolinux.img
          files: |
            ./demolinux-*
            ./sha256sums.txt

  release:
    if: github.ref == 'refs/heads/master'
    permissions: write-all # for releasing
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up pacman
        run: ./.github/setup-pacman.sh

      - name: Build an image
        run: ./demolinux build

      - name: Run tests
        run: ./demolinux tests

      - name: Split image into chunks
        run: |
          split -b 2GB out/demolinux*.img demolinux-

      - name: Generate checksums file
        run: |
          sha256sum demolinux-* out/demolinux*.img > sha256sums.txt

      - name: Publish release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: refs/tags/master-${{ github.sha }}
          release_name: Release build
          body: |
            Automatically built from GitHub actions, from the master branch.
            Shouldn't be unstable.
            The image was split into smaller chunks to fit in GitHub releases, you can reassemble it with cat:
              cat demolinux-* > demolinux.img
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "demolinux-*;sha256sums.txt"
          release_id: ${{ steps.create_release.outputs.id }}
